#!/usr/bin/env bundle exec ruby

require 'optparse'
require_relative 'printer'

options = {}

OptionParser.new do |parser|
  parser.on("-m", "--message MESSAGE", "Message to be printed.") do |value|
    options[:message] = value
  end

  parser.on("-a", "--ascii", "Print image in ascii art.") do | |
    options[:mode] = "ascii"
  end

  parser.on("-p", "--pixel", "Print image with colorful pixels.") do | |
    options[:mode] = "colorful"
  end

  parser.on("-h", "--help", "Display this help.") do | |
    print parser
    options[:help] = true
  end
end.parse!

Printer.new(options)
